### ISSUE TITLE
Remove class names

### ISSUE THREAD

**Issue by jhnns** [peerigon/nodeclass#12]
It is possible to retrieve the filename of the requiring file via this nasty trick

``` javascript
    try {
        throw new Error();
    } catch (err) {
        filename = err.stack
            .split("\n")[2]
            .match(/\((.*)\)/)[1]
            .replace(/:[0-9]+:[0-9]+$/g, "");
    }
```

Thus we can derive the class name from the filename which is more comfortable because when you're changing a class name, you don't have to do this at three different places.

**Comment by meaku** [comment]
But that's nasty.. maybe we should keep it, the way it is. Although we could retrieve the name automatically if there is nothing defined.

**Comment by jhnns** [comment]
Mhmmm ... I didn't like this trick because try-catch decreases the performance. But the impact actually is very small (~0,001ms slower when compiling a class).

I don't like changing the name at three different places.

**Comment by jhnns** [comment]
nodeclass got replaced by [alamid-class](/peerigon/alamid-class)
