### ISSUE TITLE
is(class).notInstanceOf(SpecificClass) is not working in SpecificClass

### ISSUE THREAD

**Issue by topa** [peerigon/nodeclass#4]
I want to use <code>notInstanceOf</code> in the _append() of the [DisplayObject](https://github.com/pandaa/alamid/blob/master/lib/client/DisplayObject.class.js). This method should except DisplayObject and kind of DisplayObjects. If you provide any other object it should throw an Error. 
But if I'm trying to check if given param with notInstanceof() if got an TypeError:

> message: "Class must be a constructor function. For native types, pass the corresponding constructor (e.g. String for strings).

This is the exact code snippet where the error happens:

```
if (is(displayObject).notInstanceOf(DisplayObject)) {
    throw new TypeError("(alamid) type error: ._append() takes only objects kind of DisplayObject.");
}
```

For more detailed information about the code please click this link to the  [DisplayObject](https://github.com/pandaa/alamid/blob/master/lib/client/DisplayObject.class.js).

**Comment by topa** [comment]
Also I'm not sure if it is a good idea that an <code>(not)instanceOf</code> method throws an TypeError. I know what you want to say with the Error: "This function only works for checking nodeclasses". But I wouldn't assume that an <code>(not)instanceOf</code> will throw an Error if I pass a wrong a type. That behavior is in my opinion to rude.

**Comment by jhnns** [comment]
Fixed. instanceOf should throw a TypeError because you can't check instanceOf without providing a class. Every other use makes not sense to me.
