### ISSUE TITLE
Provide fluent setter/getter

### ISSUE THREAD

**Issue by jhnns** [peerigon/nodeclass#8]
I recently stumbled upon a nice way to implement setters and getters in JavaScript. Although I have seen it often (while using jQuery for example) I haven't thought about it yet. The style looks like:

``` javascript
// Classic setter and getter
$elem.setCss("background", "green");
$elem.getCss("color");

// Fluent setter and getter
$elem.css("background", "green");       // sets "green"
$elem.css("color");                     // returns "green"
```

I always didn't like the idea of creating automatic setters and getters, because it is magic. On the other hand it is not possible to have property scoping (private/protected/public) **and** direct property access in one single object - so I had to use methods for setting and getting.

But using setters - especially if they're not chainable - is always producing bloated lines of codes which affect readability. That's why I came to the idea of providing this nice fluent solution.

But I think nodeclass should provide both ways, the classic and the fluent. Setters have one big advantage: If I want to validate the incoming value later I just have to add the validation code without changing the API. If I had exposed the property directly, I would have to break the API in order to transform the property into a setter and getter. That's why the new fluent setter/getter should internally call the setter or getter accordingly.

This way the developer can choose between different styles according to his/her preference and just has to modify **one** method, to add a specific action.

The only con I can imagine is that the exposed API in the debugging output is polluted with more methods. What do you think? @topa @meaku

**Comment by jhnns** [comment]
By the way: I am heavily influenced by [this article](http://coding.smashingmagazine.com/2012/10/09/designing-javascript-apis-usability/) :smile:

**Comment by topa** [comment]
> I always didn't like the idea of creating automatic setters and getters, because it is magic

... and it breaks IDE support. However I don't know any IDE that provides a good autocomplete for JavaScript.

> But using setters - especially if they're not chainable - is always producing bloated lines of codes which affect readability. That's why I came to the idea of providing this nice fluent solution.

```
someClass.init({
    option1: "any value"
    option2: ["any value"]
});
```

VS

```
someClass
    .set("option1", "any value")
    .set("option2", ["any value"]), 
```

VS

```
someClass
    .setOption1("any value")
    .setOption2(["any value"]);
```

I don't like passing an Object, cause I never can remember the options. This is a real issue if a project relies on 50++ modules.
Fluent setters/getters lead to the problem that a class isn't telling you anything what you can do with it and there is no chance for IDE support.
I really never got the problem of setters. Sure, you have to write them in your class. But you're writing them once while the class is meant to be used unlimited times. I prefer setters, cause they are telling me what I can do with a Class.

The optimum for me is "usual" setters + IDE support + chaining.

**Comment by jhnns** [comment]
If you want IDE support you can always write the setter/getters explicitly which override the automatic setters/getters. `nodeclass` has to provide automatic setters/getters because it's simply not possible without them.

But I think you haven't posted my suggestion:

``` javascript
// Setter
someClass
     .option1(value)
     .option2(value);

// Getter
someClass.option1();
someClass.option2();
```

My suggestion was to provide both automatic setter/getter styles. `setOption1` and just `option1` without `set` and `get`. If you want to override a setter/getter you just have to override `setOption1`, because `option1` calls internally `setOption1`. 

This is not a big deal, but thus everyone can use his/her preferred style of API. Some people are allergic against `set` and `get`. :wink:

**Comment by meaku** [comment]
Sounds nice. And it's a workaround for setting properties directly, because it improves readability. 

```
someClass.name = "hans";


someClass.name("hans")
```

**Comment by jhnns** [comment]
I'm not sure if we should decide for just one style or keep both. But I'm starting to dislike these Java-like setters and getters, too.

**Comment by topa** [comment]
I don't mind as long your classes are telling me a story about what I can do with them, so that I don't have to use documentation ....

**Comment by jhnns** [comment]
I think nodeclass should use the [getter and setter feature](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Object/defineProperty#ie8-specific) of JavaScript which is available on all newer JavaScript engines. If you're haking only in node you can rely on this feature.

**Comment by topa** [comment]
> If you're haking only in node you can rely on this feature.

But that is not the case :) So I don't think so!

**Comment by jhnns** [comment]
nodeclass can be used node-only, so I do think so. (nodeclass is not alamid)

**Comment by topa** [comment]
But one advantage of alamid is to write code on the server like on the client. And we're using nodeclass mainly for alamid. Currently nodeclass is part of alamid.

**Comment by jhnns** [comment]
nodeclass got replaced by [alamid-class](/peerigon/alamid-class)
