### ISSUE TITLE
Prefixes or not, that's the question

### ISSUE THREAD

**Issue by jhnns** [peerigon/nodeclass#9]
A long time ago I had the presumption that nodeclass doesn't expose property prefixes like `_`, `__` and `$`. So when accessing a property **inside** the class, all properties were named exactly like you defined it (**with** prefix). But from **outside** (e.g. another file) you accessed them **without** the prefix.

But now protected properties have the underscore-prefix. We introduced this, because protected is somehow **inside** the class and we wanted to indicate, that a specific property is protected.

But static properties for example have always been without prefix. Now I'm thinking, that probably all properties should keep their original prefix. But I'm not sure about this, so let's discuss it:
### Pro
- Better IDE auto-completion
- Clear rule without exceptions
### Con
- Harder to read code because of "strange" chars like `_` and `$`

What do you think @topa @meaku? Sure, we currently have other problems than this, but I think we should make a thought-out decision soon so we don't have to stick with unlogical and deprecated decisions.

**Comment by topa** [comment]
**Pro**

> Better IDE auto-completion

If I try to use a static method my IDE suggest me the <code>$methodName</code> :+1: 

> Clear rule without exceptions

If I don't have to remove the $ it is pretty straight forward. I don't lose time by doing this stupid task. :+1:

> Harder to read code because of "strange" chars like _ and $

<code>_</code> and <code>__</code> are only used internally in a class. So it shouldn't bother the user of a class. And in the class it makes the scoping and inheriting clear.

**Comment by jhnns** [comment]
Underscore is ok, I think. But what's with static properties, with the `$`-symbol?

Ok, you're a PHP hacker, you're used to it :wink:

**Comment by topa** [comment]
Wow ... I just had to look at the [PHP Docs](http://php.net/manual/en/language.variables.php) if I really have to use a $ for var definition ... I've totally forgotten that ^^

> Underscore is ok, I think. But what's with static properties, with the $-symbol?

You mean inside classes? I think like the underscores it is ok, because it tells me that I', using a static function.

**Comment by jhnns** [comment]
Not only for inside the classes. Every time you use a static function:

``` javascript
User.$findById(2, function () { ... });
Service.$define({ ... });
```

It's ugly - but it's logical.

**Comment by topa** [comment]
Seems to be only optically ugly (for you) but not semantically ... I think it makes reading the code easier. I would say that it is in someway even beautiful :)

**Comment by jhnns** [comment]
But it's not really necessary. The uppercase letter already indicates that it is a class, so it must be a static method.

**Comment by topa** [comment]
Okay that's true. So it should be

```
Service.define( { /*... */ )}
```

Conclusion?

**Comment by jhnns** [comment]
So it would be the way like it is. I already know @meaku s answer :wink:. I will keep it open and think about it for a while, but I'm afraid the current solution is the best (although it's not the most logical).

**Comment by meaku** [comment]
I like `Service.define` without **$**

**Comment by jhnns** [comment]
Let's keep it that way.
